### ISSUE TITLE
AttributeError: module 'simplesqlite' has no attribute 'connect_sqlite_memdb'

### ISSUE THREAD

**Issue by ThomasHeinrichSchmidt** [thombashi/sqlitebiter#42] opened 2017-08-11 14:48 UTC
Under Windows 10 using   
`C:\> sqlitebiter.exe -v   file   Schema1.json` 
from sqlitebiter_win_x64.zip I always get the above message - whatever syntax I try or whatever .json file I choose.
I'm using the samples from the Python docu regarding 5.3.4. JSON Loader Classes, see 
[Schema.zip](https://github.com/thombashi/sqlitebiter/files/1218189/Schema.zip).
![issue](https://user-images.githubusercontent.com/8068047/29218342-ce1de210-7eb4-11e7-8a39-9ff18155f1e9.png)

**Comment by thombashi** [comment] 2017-08-11 15:36
Thank you for your report.

The problem caused by improperly packaging `sqlitebiter 10.2` binary file for Windows.
I've replaced the binary file to fixed version.

```
>sqlitebiter.exe -v file Schema1.json
[INFO] sqlitebiter file: convert 'Schema1.json' to 'Schema1 (attr_a INTEGER, attr_b REAL, attr_c TEXT)' table

```

Would you retry with this version?

**Comment by ThomasHeinrichSchmidt** [comment] 2017-08-11 15:41
Yes please, your [Download](https://github.com/thombashi/sqlitebiter/releases) seems not to have changed ...

**Comment by ThomasHeinrichSchmidt** [comment] 2017-08-11 15:51
Thank you very much Tsuyoshi san,
for your very fast answer.
I just downloaded your new file and I'll try again ...
But I have to wait until my virus scanner releases the file :-)
I'll keep you posted...
--thomas.

Tsuyoshi Hombashi schrieb am 11.08.2017 um 17:36:

**Comment by ThomasHeinrichSchmidt** [comment] 2017-08-12 09:38
Works like a charm now.
Thank you very much Tsuyoshi san, issue can be closed.
![issue 42-ok](https://user-images.githubusercontent.com/8068047/29239596-ab39fbc8-7f52-11e7-82bd-1e8df43fdc27.png)
--thomas.

**Comment by thombashi** [comment] 2017-08-12 13:35
I'm glad that works for you.
I'll close the issue then.

**Closed by thombashi** 2017-08-12 13:35 UTC
